name: german-credit-ci-env
channels:
  - conda-forge
dependencies:
  - python=3.12.7
  - pip
  - pip:
      - mlflow==2.19.0
      - numpy
      - pandas
      - scikit-learn==1.5.2
      - matplotlib
      - joblib
